#markdown: redcarpet
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
#highlighter: pygments

markdown: kramdown
highlighter: rouge
kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  enable_coderay: false
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#google_analytics_id: UA-XXXXXXXX-X

repository: https://github.com/fagstoff/IT1
edit_url_base: https://github.com/fagstoff/IT1/blob/master/
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true

name: IT1 • Læremidler for informasjonsteknologifaget
description: Frie læremidler for IT1
baseurl: /it1

gems:
  - jekyll-feed

timezone: Europe/Oslo
